---
version: 1
service:
  name: '{{ env "bamboo_deploy_environment" }}-{{ env "bamboo_shortPlanName" }}'
  shortname: ""
  owner: lab
deployment:
  strategy: blueGreen
health:
  delayseconds: 0
  path: "/"
  port: 80
ports:
  - 80
ingress:
  hosts:
    - host: '{{ env "bamboo_deploy_host" }}'
      path: /project/opendatacam/
      public: true
      stripPrefix: /project/opendatacam/
