name: Build -> Push -> Publish project

on:
  push:
    branches:
      - master

jobs:
  build_container:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA::8})
      - name: Build and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          APP_VERSION: ${{ env.RELEASE_VERSION }}
          RELEASE_DATE: $(date +\"%Y/%m/%d\")
        with:
          name: opendatacam/opendatacam-website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: APP_VERSION,RELEASE_DATE
          tags: "latest,${{ env.RELEASE_VERSION }}"
  update_droplet:
    needs: [build_container]
    runs-on: ubuntu-latest
    name: Update DigitalOcean droplet
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Create ssh key
        env:
          GH_DO_SSH_KEY: ${{ secrets.GH_DO_SSH_KEY }}
        shell: bash
        run: |
          mkdir ~/.ssh
          echo "$GH_DO_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_DROP_HOST }} >> ~/.ssh/known_hosts
      - name: Update DigitalOcean drop via doctl
        shell: bash
        run: |
          doctl compute ssh drop001 \
            --ssh-command /www/docker/server_infrastructure/update.sh \
            --ssh-key-path ~/.ssh/id_rsa
